In [ ]:
import pandas as pd

dct = {
    'name' : ['Tom', 'nick', 'krish', 'jack'],
    'age' : [20, 21, 19, 18],
    'roll' : [1, 2, 3, 4]
}

df = pd.DataFrame(dct)
df1 = pd.DataFrame(dct, index=['a','b','c','d'])

display(df)
display(df1)
print(df)

    name  age  roll
0    Tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
a    Tom   20     1
b   nick   21     2
c  krish   19     3
d   jack   18     4

    name  age  roll
0    Tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

In [ ]:
df = pd.read_csv('/content/student_data.csv')
display(df.head(3))
display(df.tail(4))
df.shape

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.0,Placed
1,4,69,5,3,8,56,100.0,Placed
2,11,60,7,6,10,45,100.0,Placed

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

(10000, 8)

In [ ]:
df = pd.read_csv('/content/student_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [ ]:
df = pd.read_csv('/content/student_data.csv')
display(df.describe())
display(df.index)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df = pd.read_csv('/content/student_data.csv')
display(df[['study_hours','attendance']])
display(df.iloc[23:25])
display(df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8])

      study_hours  attendance
0               7          56
1               4          69
2              11          60
3               8          99
4               5          52
...           ...         ...
9995            2          58
9996            7          98
9997           10          44
9998           10          75
9999            2          70

[10000 rows x 2 columns]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
23,5,88,6,3,16,43,100.00,Placed
24,1,86,8,1,4,78,91.65,Placed

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [ ]:
#remove rows and columns

import pandas as pd
df.drop(rows)